{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.daemonset_zun_compute }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.zun }}

{{- $mounts_zun_compute := .Values.pod.mounts.zun_compute.zun_compute }}
{{- $mounts_zun_compute_init := .Values.pod.mounts.zun_compute.init_container }}

{{- $serviceAccountName := "zun" }}
{{ tuple $envAll $dependencies $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: zun-compute
spec:
{{ tuple $envAll "zun_compute" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "zun" "zun_compute" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      nodeSelector:
        {{ .Values.labels.agent.zun_compute.node_selector_key }}: {{ .Values.labels.agent.zun_compute.node_selector_value }}
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
{{- if .Values.ceph.enabled }}
      initContainers:
{{ tuple $envAll $dependencies $mounts_zun_compute_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: ceph-keyring-placement
          image: {{ .Values.images.tags.zun_compute }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          securityContext:
            runAsUser: 0
          env:
            - name: CEPH_CINDER_USER
              value: "{{ .Values.ceph.cinder_user }}"
            {{- if .Values.ceph.cinder_keyring }}
            - name: CEPH_CINDER_KEYRING
              value: "{{ .Values.ceph.cinder_keyring }}"
            {{ end }}
            - name: zun_CEPH_SECRET_UUID
              value: "{{ .Values.ceph.secret_uuid }}"
          command:
            - /tmp/ceph-keyring.sh
          volumeMounts:
            - name: etcceph
              mountPath: /etc/ceph
            - name: zun-bin
              mountPath: /tmp/ceph-keyring.sh
              subPath: ceph-keyring.sh
              readOnly: true
            - name: ceph-keyring
              mountPath: /tmp/client-keyring
              subPath: key
              readOnly: true
{{- end }}
      containers:
        - name: zun-compute
          image: {{ .Values.images.tags.zun_compute }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.compute | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          securityContext:
            privileged: true
            runAsUser: 0
          {{- if .Values.ceph.enabled }}
          env:
            - name: CEPH_CINDER_USER
              value: "{{ .Values.ceph.cinder_user }}"
            {{- if .Values.ceph.cinder_keyring }}
            - name: CEPH_CINDER_KEYRING
              value: "{{ .Values.ceph.cinder_keyring }}"
            {{ end }}
            - name: zun_CEPH_SECRET_UUID
              value: "{{ .Values.ceph.secret_uuid }}"
          {{ end }}
          command:
            - /tmp/zun-compute.sh
          volumeMounts:
            - name: zun-bin
              mountPath: /tmp/zun-compute.sh
              subPath: zun-compute.sh
              readOnly: true
            - name: zun-etc
              mountPath: /etc/zun/zun.conf
              subPath: zun.conf
              readOnly: true
            - name: zun-etc
              mountPath: /etc/zun/qemu.conf
              subPath: qemu.conf
              readOnly: true
            - mountPath: /lib/modules
              name: libmodules
              readOnly: true
            - name: var-lib-zun
              mountPath: /var/lib/zun
            - name: var-lib-nova
              mountPath: /var/lib/nova
            - name: run
              mountPath: /run
            - name: dev
              mountPath: /dev
            - name: cgroup
              mountPath: /sys/fs/cgroup
            - name: machine-id
              mountPath: /etc/machine-id
              readOnly: true
            {{- if .Values.ceph.enabled }}
            - name: etcceph
              mountPath: /etc/ceph
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-keyring
              mountPath: /tmp/client-keyring
              subPath: key
              readOnly: true
            {{- end }}
{{ if $mounts_zun_compute_init.volumeMounts }}{{ toYaml $mounts_zun_compute_init.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: zun-bin
          configMap:
            name: zun-bin
            defaultMode: 0555
        - name: zun-etc
          configMap:
            name: zun-etc
            defaultMode: 0444
        {{- if .Values.ceph.enabled }}
        - name: etcceph
          emptyDir: {}
        - name: ceph-etc
          configMap:
            name: ceph-etc
            defaultMode: 0444
        - name: ceph-keyring
          secret:
            secretName: pvc-ceph-client-key
        {{ end }}
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: var-lib-zun
          hostPath:
            path: /var/lib/zun
        - name: var-lib-nova
          hostPath:
            path: /var/lib/nova
        - name: run
          hostPath:
            path: /run
        - name: dev
          hostPath:
            path: /dev
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: machine-id
          hostPath:
            path: /etc/machine-id
{{ if $mounts_zun_compute_init.volumes }}{{ toYaml $mounts_zun_compute_init.volumes | indent 8 }}{{ end }}
{{- end }}
