# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    check:
      jobs:
        - openstack-helm-linter
        - openstack-helm-dev-deploy-ceph:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-helm-dev-deploy-nfs:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-helm-multinode-ubuntu:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        #NOTE(portdirect): Voting disabled until ipcalc package issue resolved.
        - openstack-helm-multinode-centos:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        #NOTE(lamt): Make fedora job non-voting until issues with gates are resolved.
        - openstack-helm-multinode-fedora:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-helm-ironic-ubuntu:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-helm-armada-fullstack-deploy:
            voting: false
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
    gate:
      jobs:
        - openstack-helm-linter:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-helm-dev-deploy-ceph:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-helm-dev-deploy-nfs:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-helm-multinode-ubuntu:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$

- job:
    name: openstack-helm-linter
    run: tools/gate/playbooks/zuul-linter.yaml
    nodeset: openstack-helm-single-node

- job:
    name: openstack-helm-dev-deploy
    timeout: 7200
    vars:
      zuul_osh_infra_relative_path: ../openstack-helm-infra/
    pre-run:
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-upgrade-host.yaml
    post-run: ../openstack-helm-infra/tools/gate/playbooks/osh-infra-collect-logs.yaml
    required-projects:
      - openstack/openstack-helm-infra
    nodeset: openstack-helm-single-node

- job:
    name: openstack-helm-dev-deploy-ceph
    parent: openstack-helm-dev-deploy
    run: tools/gate/playbooks/dev-deploy-ceph.yaml

- job:
    name: openstack-helm-dev-deploy-nfs
    parent: openstack-helm-dev-deploy
    run: tools/gate/playbooks/dev-deploy-nfs.yaml

- job:
    name: openstack-helm-multinode
    timeout: 7200
    vars:
      zuul_osh_infra_relative_path: ../openstack-helm-infra/
    pre-run:
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-upgrade-host.yaml
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-deploy-docker.yaml
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-build.yaml
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-deploy-k8s.yaml
    run: tools/gate/playbooks/multinode-deploy.yaml
    post-run: ../openstack-helm-infra/tools/gate/playbooks/osh-infra-collect-logs.yaml
    required-projects:
      - openstack/openstack-helm-infra

- job:
    timeout: 9600
    vars:
        zuul_osh_infra_relative_path: ../openstack-helm-infra/
    name: openstack-helm-armada-fullstack-deploy
    pre-run:
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-upgrade-host.yaml
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-deploy-docker.yaml
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-build.yaml
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-deploy-k8s.yaml
    run: tools/gate/playbooks/armada-fullstack-deploy.yaml
    post-run:
      - ../openstack-helm-infra/tools/gate/playbooks/osh-infra-collect-logs.yaml
      - tools/gate/playbooks/gather-armada-manifests.yaml
    required-projects:
        - openstack/openstack-helm-infra
    nodeset: openstack-helm-five-node-ubuntu

- job:
    name: openstack-helm-multinode-ubuntu
    parent: openstack-helm-multinode
    nodeset: openstack-helm-five-node-ubuntu

- job:
    name: openstack-helm-multinode-centos
    parent: openstack-helm-multinode
    nodeset: openstack-helm-five-node-centos

- job:
    name: openstack-helm-multinode-fedora
    parent: openstack-helm-multinode
    nodeset: openstack-helm-five-node-fedora

- job:
    name: openstack-helm-ironic-ubuntu
    parent: openstack-helm-multinode
    nodeset: openstack-helm-ubuntu
    run: tools/gate/playbooks/ironic-deploy.yaml
